import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useSession, signOut } from 'next-auth/react';
import type { NextPage } from 'next';
import Head from 'next/head';


export default function TestNFTAttributes() {
  const { data: session, status } = useSession();
  return (
    <div >
      <Head>
        <title>RainbowKit SIWE NextAuth Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1 >
          Welcome to RainbowKit SIWE NextAuth!
        </h1>

        <div style={{ margin: '20px 0' }}>
          <ConnectButton />
        </div>

        {status === 'loading' && <p>Loading session...</p>}

        {status === 'authenticated' && session && (
          <div >
            <h2>Session Information:</h2>
            <p>
              <strong>Signed in as:</strong> {(session.user as any)?.name || 'N/A'}
            </p>
            <p>
              <strong>Address:</strong> {(session as any)?.address || 'N/A'}
            </p>
            {/* You can access other session properties here if you've added them */}
            {/* <pre>{JSON.stringify(session, null, 2)}</pre> */}
            <button onClick={() => signOut()} >
              Sign Out
            </button>
          </div>
        )}

        {status === 'unauthenticated' && (
          <p>Please connect your wallet and sign in.</p>
        )}
      </main>
    </div>
  );
}
